FROM java:8
VOLUME /tmp
EXPOSE 9099
ADD target/Consumption_Calculator-0.0.1-SNAPSHOT.jar Consumption_Calculator-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Consumption_Calculator-0.0.1-SNAPSHOT.jar"]